# Generated by Django 2.2.7 on 2019-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20191128_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='ships',
        ),
        migrations.AddField(
            model_name='board',
            name='ships_data',
            field=models.TextField(default='{"ships": [], "hitcoords": []}'),
        ),
    ]
