# Generated by Django 2.2.7 on 2019-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20191201_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='start_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
