# Generated by Django 2.2.7 on 2019-12-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20191208_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='board1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board1', to='front.Board'),
        ),
        migrations.AlterField(
            model_name='games',
            name='board2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board2', to='front.Board'),
        ),
    ]
